name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: CMake Build
      run: make lib

  cppcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create CPPcheck Workspace
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq cppcheck
    - name: Static Defect Analysis using CPPcheck
      run: |
        cppcheck --version
        make clean
        make cppcheck

  flawfinder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create Flawfinder Workspace
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq flawfinder
    - name: Static Defect Analysis using flawfinder
      run: |
        flawfinder --version
        make clean
        make flawfinder

  codespell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create codespell Workspace
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq codespell
    - name: Static Spelling Analysis using codespell
      run: make spell

  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create Build Environment
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq lcov
    - name: Run Unit Test with Code Coverage
      run: make test
